import type { ChatMessage, HandRaise, Persona } from "@/types";

export interface ExportOptions {
  includeTimestamps: boolean;
  includeHandRaises: boolean;
  includePersonaInstructions: boolean;
}

export interface ExportInput {
  messages: ChatMessage[];
  personas: Persona[];
  topic: string;
  tone: string;
  mode: "chat" | "debate";
  handRaises: HandRaise[];
  exportedAt?: Date;
  options: ExportOptions;
}

const pad = (n: number) => String(n).padStart(2, "0");

function stamp(d: Date): string {
  return (
    `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}` +
    `-${pad(d.getHours())}${pad(d.getMinutes())}`
  );
}

function timeShort(iso: number): string {
  const d = new Date(iso);
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function exportFilename(mode: string, ext: string, now = new Date()): string {
  return `personaplex-${mode}-${stamp(now)}.${ext}`;
}

export function downloadText(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function speakerHeading(message: ChatMessage, personas: Persona[]): { emoji: string; name: string } {
  if (message.role === "user") return { emoji: "👤", name: "You" };
  if (message.personaId === "__moderator__") return { emoji: "🎤", name: "Moderator" };
  const persona = personas.find((p) => p.id === message.personaId);
  return { emoji: persona?.avatar ?? "🤖", name: persona?.name ?? "Assistant" };
}

function visibleMessages(messages: ChatMessage[]): ChatMessage[] {
  // Drop empty failed turns and empty placeholders from exports.
  return messages.filter((m) => !(m.failed || m.content.trim() === ""));
}

/** Rich markdown: header, participants table, transcript, optional appendices. */
export function buildMarkdownTranscript(input: ExportInput): string {
  const { messages, personas, topic, tone, mode, handRaises, exportedAt = new Date(), options } = input;
  const lines: string[] = [];

  lines.push("# 🎭 PersonaPlex Transcript");
  lines.push("");
  lines.push(
    `> **Mode:** ${mode === "debate" ? "Debate" : "Chat"} · **Tone:** ${tone}  `
  );
  if (topic) lines.push(`> **Topic:** ${topic}  `);
  lines.push(`> **Date:** ${exportedAt.toLocaleString()}`);

  if (personas.length > 0) {
    lines.push("");
    lines.push("## Participants");
    lines.push("");
    lines.push("| | Persona | Tone | Expertise |");
    lines.push("|---|---|---|---|");
    for (const p of personas) {
      lines.push(`| ${p.avatar} | **${p.name}** | ${p.tone} | ${p.expertiseTags.join(", ") || "—"} |`);
    }
  }

  lines.push("");
  lines.push("## Transcript");

  for (const m of visibleMessages(messages)) {
    if (m.kind === "event") {
      lines.push("");
      lines.push(`*${m.content.trim()}*`);
      continue;
    }
    const { emoji, name } = speakerHeading(m, personas);
    lines.push("");
    lines.push(`### ${emoji} ${name}`);
    if (options.includeTimestamps) {
      lines.push("");
      lines.push(`*${timeShort(m.timestamp)}*`);
    }
    lines.push("");
    lines.push(m.content.trim());
  }

  if (options.includeHandRaises && handRaises.length > 0) {
    lines.push("");
    lines.push("## Appendix — Last Hand-Raise Evaluation");
    lines.push("");
    lines.push("| Persona | Raised | Confidence | Snippet |");
    lines.push("|---|---|---|---|");
    for (const h of [...handRaises].sort((a, b) => b.confidence - a.confidence)) {
      const persona = personas.find((p) => p.id === h.personaId);
      lines.push(
        `| ${persona?.avatar ?? ""} ${persona?.name ?? h.personaId} | ${h.wantsToSpeak ? "🖐️" : "—"} | ${Math.round(h.confidence * 100)}% | ${h.snippet || "—"} |`
      );
    }
  }

  if (options.includePersonaInstructions && personas.length > 0) {
    lines.push("");
    lines.push("## Appendix — Persona Instructions");
    for (const p of personas) {
      lines.push("");
      lines.push(`### ${p.avatar} ${p.name}`);
      lines.push("");
      lines.push("```text");
      lines.push(p.systemPrompt);
      lines.push("```");
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("<sub>Generated by PersonaPlex · 100% client-side transcript</sub>");
  lines.push("");
  return lines.join("\n");
}

/** Clean markdown: just the conversation, no metadata blocks. */
export function buildMarkdownClean(input: ExportInput): string {
  const { messages, personas } = input;
  const lines: string[] = [];
  for (const m of visibleMessages(messages)) {
    if (m.kind === "event") {
      lines.push(`*${m.content.trim()}*`);
      lines.push("");
      continue;
    }
    const { emoji, name } = speakerHeading(m, personas);
    lines.push(`**${emoji} ${name}:**`);
    lines.push("");
    lines.push(m.content.trim());
    lines.push("");
  }
  return lines.join("\n").trimEnd() + "\n";
}

interface JsonExport {
  schema: "personaplex.export.v1";
  exportedAt: string;
  session: { mode: string; topic: string; tone: string };
  participants: {
    id: string;
    name: string;
    avatar: string;
    tone: string;
    expertiseTags: string[];
    systemPrompt?: string;
  }[];
  handRaiseEvaluation?: HandRaise[];
  messages: {
    role: string;
    personaId?: string;
    personaName?: string;
    content: string;
    timestamp: string;
    failed?: boolean;
  }[];
}

/** Lossless JSON export (schema-versioned, re-importable later). */
export function buildJsonExport(input: ExportInput): string {
  const { messages, personas, topic, tone, mode, handRaises, exportedAt = new Date(), options } = input;

  const json: JsonExport = {
    schema: "personaplex.export.v1",
    exportedAt: exportedAt.toISOString(),
    session: { mode, topic, tone },
    participants: personas.map((p) => ({
      id: p.id,
      name: p.name,
      avatar: p.avatar,
      tone: p.tone,
      expertiseTags: p.expertiseTags,
      ...(options.includePersonaInstructions ? { systemPrompt: p.systemPrompt } : {}),
    })),
    ...(options.includeHandRaises && handRunsNonEmpty(handRaises)
      ? { handRaiseEvaluation: handRaises }
      : {}),
    messages: visibleMessages(messages).map((m) => ({
      role: m.kind === "event" ? "event" : m.role,
      ...(m.personaId ? { personaId: m.personaId } : {}),
      ...(() => {
        const s = speakerHeading(m, personas);
        return { personaName: `${s.emoji} ${s.name}` };
      })(),
      content: m.content.trim(),
      timestamp: new Date(m.timestamp).toISOString(),
      ...(m.failed ? { failed: true } : {}),
    })),
  };

  return JSON.stringify(json, null, 2);
}

function handRunsNonEmpty(handRaises: HandRaise[]): boolean {
  return handRaises.length > 0;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Minimal styled HTML for the print/PDF path (opened in a popup window). */
export function buildPrintHtml(input: ExportInput): string {
  const { messages, personas, topic, tone, mode, exportedAt = new Date() } = input;
  const body: string[] = [];

  body.push(`<h1>🎭 PersonaPlex</h1>`);
  body.push(
    `<p class="meta">${mode === "debate" ? "Debate" : "Chat"} · ${escapeHtml(tone)}${
      topic ? ` · ${escapeHtml(topic)}` : ""
    } · ${escapeHtml(exportedAt.toLocaleString())}</p>`
  );

  for (const m of visibleMessages(messages)) {
    if (m.kind === "event") {
      body.push(`<p class="event">${escapeHtml(m.content.trim())}</p>`);
      continue;
    }
    const { emoji, name } = speakerHeading(m, personas);
    const t = new Date(m.timestamp);
    body.push(
      `<h3>${emoji} ${escapeHtml(name)} <span class="t">${pad(t.getHours())}:${pad(t.getMinutes())}</span></h3>`
    );
    body.push(`<div class="msg">${escapeHtml(m.content.trim()).replace(/\n/g, "<br/>")}</div>`);
  }

  return `<!doctype html><html><head><meta charset="utf-8"/><title>PersonaPlex Transcript</title>
<style>
  body{font-family:ui-sans-serif,system-ui,sans-serif;max-width:760px;margin:0 auto;padding:32px 24px;color:#16181d;line-height:1.55}
  h1{font-size:1.4rem;margin:0 0 4px}
  h3{font-size:0.95rem;margin:18px 0 4px}
  .meta{color:#5a6072;font-size:0.85rem;margin:0}
  .t{color:#8a90a0;font-size:0.75rem;font-weight:400;margin-left:6px}
  .msg{white-space:normal;border-left:3px solid #e4e6ee;padding:2px 0 2px 12px}
  .event{text-align:center;color:#7a8194;font-size:0.8rem;font-style:italic;margin:10px 0}
</style></head><body>${body.join("\n")}</body></html>`;
}

export function openPrintWindow(html: string): boolean {
  const w = window.open("", "_blank", "width=820,height=920");
  if (!w) return false;
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  // Give the popup a tick to lay out before the print dialog opens.
  setTimeout(() => w.print(), 250);
  return true;
}
